# Generated by Django 5.0 on 2026-03-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='normalized_lr',
            field=models.CharField(blank=True, db_index=True, help_text='Normalized LR number without spaces or LR prefixes for accurate searching', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='title_system',
            field=models.CharField(blank=True, help_text='System type: LR or BLOCK', max_length=20, null=True),
        ),
    ]
