# Generated by Django 5.0 on 2026-03-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0002_land_normalized_lr_land_title_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='court_station',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='defendant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='judgment_type',
            field=models.CharField(blank=True, help_text='Judgment type: Ruling or Judgment', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='plaintiff',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='year_filed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
