# Generated by Django 5.0 on 2026-03-05 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0003_land_court_station_land_defendant_land_judgment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchableReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_text', models.CharField(db_index=True, max_length=255)),
                ('reference_type', models.CharField(choices=[('LR', 'LR Number'), ('BLOCK', 'Block Number'), ('PLOT', 'Plot Number'), ('CERTIFICATE', 'Certificate Number'), ('ALLOTMENT', 'Allotment Number')], max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary reference from original data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchable_references', to='lands.land')),
            ],
            options={
                'indexes': [models.Index(fields=['reference_text', 'reference_type'], name='lands_searc_referen_a20bd3_idx')],
            },
        ),
    ]
