# Generated by Django 5.0 on 2026-02-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegalEmailApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal/Individual Use"),
                            ("business", "Business/Firm Use"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        choices=[
                            ("lawyer", "Lawyer"),
                            ("judge", "Judge"),
                            ("legal_assistant", "Legal Assistant"),
                            ("law_student", "Law Student"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "lsk_admission_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("current_email", models.EmailField(max_length=254)),
                (
                    "desired_email",
                    models.CharField(
                        help_text="Username part before @legal.ke", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
