# Generated by Django 5.0 on 2026-02-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lands", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_number", models.CharField(db_index=True, max_length=255)),
                ("case_name", models.TextField()),
                ("year", models.IntegerField()),
                ("court", models.CharField(max_length=255)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("parties", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lands",
                    models.ManyToManyField(related_name="cases", to="lands.land"),
                ),
            ],
        ),
    ]
