# Generated by Django 5.0 on 2026-02-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
