# Generated by Django 5.0 on 2026-02-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0002_alter_case_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="defendant",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="plaintiff",
            field=models.TextField(blank=True, null=True),
        ),
    ]
