# Generated by Django 5.0 on 2026-06-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["category", "order", "title"]},
        ),
        migrations.AddField(
            model_name="blogpost",
            name="category",
            field=models.CharField(
                choices=[
                    ("due_diligence", "Due Diligence"),
                    ("purchase", "Purchase"),
                    ("transfer", "Transfer"),
                    ("caution", "Caution"),
                ],
                db_index=True,
                default="due_diligence",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="order",
            field=models.IntegerField(
                default=0, help_text="Position within its category"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
