# Generated by Django 5.0 on 2026-03-18 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content",
                    models.TextField(
                        help_text="Address a real user concern or question"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of the title", unique=True
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Brief summary of the article",
                        max_length=500,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order within category"
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        help_text="Explain what stage of the journey this represents"
                    ),
                ),
                (
                    "tagline",
                    models.TextField(
                        help_text="A bold, memorable line that captures user emotion + intent"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order for categories"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["order", "title"],
            },
        ),
        migrations.DeleteModel(
            name="BlogPost",
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="blogs.category",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="article",
            unique_together={("category", "slug")},
        ),
    ]
