# Generated by Django 5.0 on 2026-06-25 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parcel_id_clean",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("normalized_lr", models.CharField(db_index=True, max_length=255)),
                ("parcel_display", models.TextField(blank=True)),
                ("parcel_id_type", models.CharField(blank=True, max_length=50)),
                ("key_scope", models.CharField(blank=True, max_length=20)),
                ("n_findings", models.IntegerField(default=0)),
                ("volumes", models.CharField(blank=True, max_length=50)),
                ("recommendations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["parcel_id_clean"],
                "indexes": [
                    models.Index(
                        fields=["normalized_lr"], name="ndungu_parc_normali_107716_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_id", models.CharField(db_index=True, max_length=255)),
                ("parcel_id_raw", models.CharField(blank=True, max_length=255)),
                ("parcel_id_type", models.CharField(blank=True, max_length=50)),
                ("flag_category", models.CharField(blank=True, max_length=255)),
                ("flag_reason", models.TextField(blank=True)),
                ("current_holder", models.TextField(blank=True)),
                ("prior_party", models.TextField(blank=True)),
                ("location", models.TextField(blank=True)),
                ("area", models.CharField(blank=True, max_length=100)),
                ("commission_recommendation", models.TextField(blank=True)),
                ("source_volume", models.CharField(blank=True, max_length=20)),
                ("source_page", models.CharField(blank=True, max_length=50)),
                ("flag_source_csv", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("needs_manual_review", models.BooleanField(default=False)),
                ("reserved_use", models.TextField(blank=True)),
                ("current_use", models.TextField(blank=True)),
                ("allocating_authority", models.TextField(blank=True)),
                ("transaction_date", models.CharField(blank=True, max_length=100)),
                ("price_kshs", models.CharField(blank=True, max_length=100)),
                ("allottee_id", models.CharField(blank=True, max_length=255)),
                ("allottee_address", models.TextField(blank=True)),
                ("legal_gazette_notice", models.TextField(blank=True)),
                ("registration_date", models.CharField(blank=True, max_length=100)),
                ("title_issue_date", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(blank=True, max_length=255)),
                ("forest", models.CharField(blank=True, max_length=255)),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="ndungu.parcel",
                    ),
                ),
            ],
            options={
                "ordering": ["source_volume", "source_page"],
                "indexes": [
                    models.Index(
                        fields=["record_id"], name="ndungu_find_record__12d061_idx"
                    )
                ],
            },
        ),
    ]
