# Generated by Django 5.0 on 2026-06-25 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ndungu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_reference",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                ("searched_parcel_id", models.CharField(max_length=255)),
                ("normalized_query", models.CharField(blank=True, max_length=255)),
                ("results_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("encumbrance_found", "Encumbrance Found"),
                            ("no_encumbrance", "No Encumbrance Recorded"),
                            ("suggestions", "Suggestions Returned"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matched_parcel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificate_logs",
                        to="ndungu.parcel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
