# Generated by Django 5.0 on 2026-07-23 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LrConversionCitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gazette_notice_no", models.CharField(blank=True, max_length=50)),
                ("gazette_vol_no", models.CharField(blank=True, max_length=100)),
                ("gazette_date", models.CharField(blank=True, max_length=100)),
                ("source_pdf", models.CharField(blank=True, max_length=255)),
                ("source_page", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "ordering": ["gazette_date"],
            },
        ),
        migrations.CreateModel(
            name="LrConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_lr_no", models.CharField(max_length=255)),
                ("normalized_old_lr", models.CharField(db_index=True, max_length=255)),
                ("new_lr_number", models.CharField(max_length=255)),
                ("normalized_new_lr", models.CharField(db_index=True, max_length=255)),
                ("new_parcel_no", models.CharField(blank=True, max_length=50)),
                ("block", models.CharField(blank=True, max_length=255)),
                ("scheme_name", models.CharField(blank=True, max_length=255)),
                ("area_ha", models.CharField(blank=True, max_length=50)),
                ("registration_unit", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["old_lr_no"],
                "indexes": [
                    models.Index(
                        fields=["normalized_old_lr"],
                        name="conversions_normali_e3f07c_idx",
                    ),
                    models.Index(
                        fields=["normalized_new_lr"],
                        name="conversions_normali_84bcc4_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="lrconversion",
            constraint=models.UniqueConstraint(
                fields=("normalized_old_lr", "normalized_new_lr"),
                name="unique_old_new_lr_pair",
            ),
        ),
        migrations.AddField(
            model_name="lrconversioncitation",
            name="conversion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="citations",
                to="conversions.lrconversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="lrconversioncitation",
            constraint=models.UniqueConstraint(
                fields=("conversion", "source_pdf", "source_page"),
                name="unique_citation_per_page",
            ),
        ),
    ]
