# Generated by Django 5.0 on 2026-07-24 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElcCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_citation",
                    models.CharField(db_index=True, max_length=500, unique=True),
                ),
                ("url_link", models.URLField(blank=True, max_length=500)),
                ("court_station", models.CharField(blank=True, max_length=255)),
                ("judgment_date", models.CharField(blank=True, max_length=100)),
                ("action", models.CharField(blank=True, max_length=50)),
                ("parties", models.TextField(blank=True)),
                ("location_details", models.TextField(blank=True)),
                ("outcome_status", models.TextField(blank=True)),
                ("sheet_timestamp", models.CharField(blank=True, max_length=50)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-synced_at"],
            },
        ),
        migrations.CreateModel(
            name="ElcCaseIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_identifier", models.CharField(max_length=255)),
                (
                    "normalized_identifier",
                    models.CharField(db_index=True, max_length=255),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="litigation.elccase",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="elccaseidentifier",
            constraint=models.UniqueConstraint(
                fields=("case", "normalized_identifier"),
                name="unique_identifier_per_case",
            ),
        ),
    ]
